version: '2'
services:
  back:
    build: .
    container_name: back
    command: npm run dev
    volumes:
      - .:/usr/src/connected-molkky
      - /usr/src/connected-molkky/node_modules
    ports:
      - "8888:8888"
  front:
    build: .
    container_name: front
    command: npm run front
    volumes:
      - .:/usr/src/connected-molkky
      - /usr/src/connected-molkky/node_modules
    depends_on:
      - back