export default {
  modalFooterButton: { margin: 0 },
  modalContent: {
    display: 'flex',
    flexDirection: 'column',
    height: 'calc(100% - 43px)',
    padding: 0,
    margin: 0,
    justifyContent: 'space-evenly',
  },
  winnerName: { textAlign: 'center', margin: 0 },
  winnerIconsContainer: { position: 'relative' },
  trophy: {
    width: '15rem',
    height: '15rem',
    display: 'block',
    margin: 'auto',
    fill: '#143746',
  },
  winnerIcon: {
    width: '3.5rem',
    marginRight: '0.6rem',
    marginLeft: '0.6rem',
    position: 'absolute',
    top: '5rem',
    left: 'calc(50% - 2.25rem)',
  },
  winnerScore: {
    position: 'absolute',
    top: 0,
    left: 'calc(50% - 2rem)',
    color: '#e2e2e2',
    fontSize: '2rem',
    textAlign: 'center',
    width: '4rem',
  },
  looserContainer: { textAlign: 'center', margin: 0 },
  loserIcon: { width: '2rem', verticalAlign: 'middle' },
};
